### ISSUE TITLE
[1장][김효중] 리액트 개발을 위해 꼭 알아야 할 자바스크립트

### ISSUE THREAD

**Issue by khj0426** [prgrms-web-devcourse/FEDC4-Modern-React-Study#10]
### 퀴즈

- 클로저는 어디서 사용되고 어떤 장점이 있나요?

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
useState에서 대표적으로 사용된다!
클로저는 정보의 은닉화를 위해 유용하게 쓸 수 있다.외부에서 접근할 수 있도록 만들려면 클로저가 유용하게 사용될 수 있다
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by hayamaster** [comment]
리액트에서는 `useState`에서 주로 사용된다.
클로저를 통해 변수에 직접적인 접근을 막아 은닉화를 시켜줄 수 있다.
반대로 클로저는 비용이 들기에 무작위로 사용하는 것은 좋지 않다.

**Comment by hyoribogo** [comment]
클로저는 민감한 정보를 은닉하여 사용할 때 유용합니다.
예시로, 디바운스나 쓰로틀링 같은 함수에도 타이머 값을 유지해 저장하는 등 사용할 수 있습니다.
외부에서 직접적으로 해당 변수에 접근해 값을 바꿀 수 없다는 장점이 있습니다.

**Comment by HeeSeok-kim** [comment]
클로저는 리액트에서 useState에 사용됩니다.
useState가 클로저로 된 이유는 브라우저 재랜더링시 상태값을 기억할수 있습니다.
