### ISSUE TITLE
[1장][주하] 리액트 개발을 위해 꼭 알아야 할 자바스크립트

### ISSUE THREAD

**Issue by hayamaster** [prgrms-web-devcourse/FEDC4-Modern-React-Study#14]
### 퀴즈

A. 터미널의 출력되는 값을 적으세요.
```typescript
const 팔진수 = 0o10
const 십육진수 = 0x21

console.log(팔진수 == (8).toString(8))
console.log(십육진수)
```

<br/>

B. 터미널의 출력되는 값을 적으세요.
```typescript
var hello = {
  greet: 'hello, 효주웅',
}

var hi1 = hello

var hi2 = {
  greet: 'hello, 효주웅',
}


console.log(hi1 === hello)
console.log(hi2.greet === hello.greet)
console.log(hi2 === hi1)
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
A : false, 33

<br/>

B : true, true, false
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by khj0426** [comment]
true
33

true
true
false

**Comment by hyoribogo** [comment]
A. 저 팔진수 ㅁ ㅗ르는데.. true?
0x21의 10진수 뭐 그런거겠죠..?

B. true true false

**Comment by HeeSeok-kim** [comment]
A  : false, 33
B :  true, true, false
