### ISSUE TITLE
[1장][효중] 리액트 개발을 위해 꼭 알아야 할 자바스크립트 (2)

### ISSUE THREAD

**Issue by khj0426** [prgrms-web-devcourse/FEDC4-Modern-React-Study#19]
### 퀴즈

다음의 코드가 어떤 결과가 나오는 지 알려주세요!
그리고 왜 이렇게 나오는지도 설명해주세요!

```js
console.log('스크립트 시작');

setTimeout(function() {
    console.log('setTimeout');
}, 0);

Promise.resolve().then(function() {
    console.log('Promise');
});

console.log('스크립트 끝');

```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
스크립트 시작 -> 스크립트 끝 => Promise -> setTimeout

JavaScript의 이벤트 루프는 현재 실행 중인 태스크가 끝나면 마이크로 태스크 큐를 먼저 확인하고, 그 후에 태스크 큐를 확인함!.
따라서 Promise (마이크로 태스크 큐에 등록)가 setTimeout (태스크 큐에 등록)보다 먼저 실행된다!.

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by HeeSeok-kim** [comment]
스크립트 시작, 스크립트 끝, Promise, setTimeout

**Comment by hyoribogo** [comment]
스크립트 시작
스크립트 끝
Promise
setTimeout

**Comment by hayamaster** [comment]
스크립트 시작, 스크립트 끝, Promise, setTimeout
설명: 콜 스택 가장 먼저 시작, 마이크로 태스크 큐, 태스크 큐 순으로 동작한다
