### ISSUE TITLE
[1장][희석] 리액트 개발을 위해 꼭 알아야 할 자바스크립트 (2)

### ISSUE THREAD

**Issue by HeeSeok-kim** [prgrms-web-devcourse/FEDC4-Modern-React-Study#23]
### 퀴즈

```js
const obj = {
  a: 1,
  b: 1,
  c: 1,
  d: 1,
  e: 1
}

const objA = {
  c: 10,
  ...obj
}
```

objA의 결과는 어떻게 되는지 적어주세요

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
{c: 1, a:1 , b:1, d:1, e:1}
전개 구문이 해당 값을 덮어쓰게 되어 C가 1로 초기화가 이뤄집니다.
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by khj0426** [comment]
{
 a:1,
b:1,
c:1,
d:1,
e:1

}

**Comment by hyoribogo** [comment]
{
  a: 1,
  b: 1,
  c: 1,
  d: 1,
  e: 1
}
