### ISSUE TITLE
[3장][주하] 리액트 훅 깊게 살펴보기

### ISSUE THREAD

**Issue by hayamaster** [prgrms-web-devcourse/FEDC4-Modern-React-Study#28]
### 퀴즈

A. 다음 코드의 출력을 작성하세요.
```typescript
function RefComponent() {
    const inputRef = useRef()

    console.log(inputRef.current)

    return <input ref={inputRef} type="text" />
}
```

<br/>

B. 아래 코드들을 참고하여 비동기로 정상 동작하는 **함수들**을 고르세용.
```typescript
// 1번
useEffect(async () => {
    const response = await fetch('http://juha.com')
} , [])

// 2번
useEffect(() => {
    async function fetchData() {
        const response = await fetch('http://juha.com')        
    }

    fetchData()
} , [])

// 3번
useEffect(() => {
    ;(async () => {
        const response = await fetch('http://juha.com')
    })()
}, [])
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
A. undefined
<br/>
useRef가 선언된 당시에는 아직 컴포넌트가 렌더링되기 전이라 return으로 컴포넌트의 DOM이 반환되기 전이므로 undefined가 된다.
<br/>
<br/>

B. 2, 3
useEffect에서 콜백 인수로 비동기로 함수를 호출할 경우 경쟁 상태(race condition)가 발생할 수 있다. 하지만 useEffect 내부에서 비동기 함수를 선언해 실행하거나, 즉시 실행 비동기 함수를 만들어 사용하는 것이 가능하다.
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by khj0426** [comment]
undefined
2번3번
