### ISSUE TITLE
[3장][희석] 리액트 훅 깊게 살펴보기 (2)

### ISSUE THREAD

**Issue by HeeSeok-kim** [prgrms-web-devcourse/FEDC4-Modern-React-Study#36]
### 퀴즈

```tsx
function App() {
	const [count, setCount] = useState(0)

	useEffect(() => {
		console.log('useEffect', count)
	},[count])

	useLayoutEffect(() => {
		console.log('useLayoutEffect', count)
	},[count])

	function handleClick() {
		setCount((prev) => prev + 1)
	}

	return (
		<>
			<h1>{count}</h1>
			<button onClick={handleClick}>+</button>
		</>
	)
}
```

위 코드의 실행순서를 작성해주세요

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
1. 리액트가 DOM을 업데이트
2. useLayoutEffect 실행
3. 브라우저에 변경 사항을 반영
4. useEffect를 실행
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

useLayoutEffect 0
useEffect 0

</div>
</details>
