### ISSUE TITLE
[3장][주하] 리액트 훅 깊게 살펴보기 (2)

### ISSUE THREAD

**Issue by hayamaster** [prgrms-web-devcourse/FEDC4-Modern-React-Study#38]
### 퀴즈

A: useReducer에서 전달받은 action을 기반으로 현재 state를 업데이트 시켜주는 것은 어떤 것일까요?
1. action
2. dispatcher
3. reducer
4. initialState
5. init

<br/>

B: 아래는 규칙이 어떤 ESLint 규칙인지 고르시오.
- 최상위에서만 훅을 호출해야 한다. 
- 리액트 함수형 컴포넌트 또는 사용자 정의 훅에서만 훅을 호출할 수 있다.
1. react-hook/rules-in-hook
2. react-hooks/rules-of-hooks
3. rules-of-hooks
4. react-hook/rule-on-hooks
5. react-hooks/rule-in-hooks

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
A: 3번
reducer는 현재 상태 state와 dispatch로부터 action을 전달받아 상태를 업데이트 시켜주는 함수이다.
<br/>
B: 2번
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by HeeSeok-kim** [comment]
<details>
<summary>A 정답</summary>
<div markdown="1">
3. reducer
</div>
</details>

<details>
<summary>B 정답</summary>
<div markdown="1">
2. react-hooks/rules-of-hooks
</div>
</details>

**Comment by khj0426** [comment]
<details>
<summary>A</summary>
<div markdown="1">
reducer
</div>
</details>
react-hook/rules-in-hook
<details>
<summary>B</summary>
<div markdown="1">

</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

A. dispatcher
B. 면접에서 물어보진 않을 것 같은데 ,.,..,

</div>
</details>
