### ISSUE TITLE
[4장][주하] 서버 사이드 렌더링

### ISSUE THREAD

**Issue by hayamaster** [prgrms-web-devcourse/FEDC4-Modern-React-Study#43]
### 퀴즈

다음 설명에 해당하는 답을 고르시오.

설명 : 서버 사이드 렌더링을 위한 리액트 API 중 리액트 컴포넌트를 기준으로 HTML 문자열을 만드는 함수. 
이 함수는 리액트에서 사용하는 추가적인 DOM 속성을 만들지 않고 순수한 HTML을 반환하며, 이때 거대한 HTML 파일이 완성될 때까지 기다린다.

1. renderToString
2. renderToNodeStream
3. renderToStaticMarkup
4. renderToStaticNodeStream

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
답: 3
<br/>
설명: renderToStaticMarkup은 renderToString과 매우 유사한 함수로 hydrate를 수행하지 않는다는 가정하에 순수한 HTML만 반환한다.
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by khj0426** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
333
</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1, 3

</div>
</details>
