### ISSUE TITLE
[4장][효중] 서버 사이드 렌더링

### ISSUE THREAD

**Issue by khj0426** [prgrms-web-devcourse/FEDC4-Modern-React-Study#45]
### 퀴즈

서버 사이드 렌더링의 장, 단점 한가지만 적어주세요

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

- 최초 페이지 진입이 비교적 빠르다.
- 검색 엔진과 SNS 공유 등의 메타데이터 가공이 쉽다.
- 누적 레이아웃 이동이 적다.

- 소스코드 작성시 항상 서버를 고려해야 한다. (window,sessionStorage 등등..)
- 적절한 서버가 구축되어 있어야 한다.
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by hayamaster** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
장점: 누적 레이아웃 이동이 적다.
단점: 소스 코드를 작성할 때 서버를 고려해야한다.
</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

장점: 서버에서 필요한 데이터를 호출할 수 있어 보안 문제에 안전하다. 메타데이터 같은 정보 제공에 유리하다. 검색 엔진 최적화에 좋다는 뜻.
단점: 라우팅 시 csr보다 깔끔한 ux 제공이 어려움. 서버까지 공부해야 해서 어려움

</div>
</details>
