### ISSUE TITLE
[4장][효리] 서버 사이드 렌더링 (2)

### ISSUE THREAD

**Issue by hyoribogo** [prgrms-web-devcourse/FEDC4-Modern-React-Study#48]
### 퀴즈

next.js 13버전 기준, _app.tsx에서 getInitialProps의 작동 방식을 활용해 최초 렌더링 시에만 동작하는 로직을 작성하기 위해, 총 3개의 조건을 충족하는 게 좋다고 합니다. 이 때 if 문에 들어갈 세 가지 조건을 간단하게 말로 적어주세요!

hint: 맨 처음 **서버**에서 렌더링을 할 때!

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

- req가 있을 때
- req.url이 `/_next`로 시작하지 않을 때
- pathname이 에러 페이지 관련된 게 아닐 때

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by khj0426** [comment]
(다음과 같이 답을 작성해 댓글로 달아주세요)
<details>
<summary>정답</summary>
<div markdown="1">
req가 있을 때, req.url이 /_next로 시작하지 않을 때 , pathname이 에러 페이지가 아닐때 
</div>
</details>
