### ISSUE TITLE
[5장][효리] 리액트와 상태 관리 라이브러리

### ISSUE THREAD

**Issue by hyoribogo** [prgrms-web-devcourse/FEDC4-Modern-React-Study#51]
### 퀴즈

1. FLUX 패턴은 기존의 [ A ] 패턴의 [ B ] 문제점을 극복하기 위해 나온 패턴이다.

2. FLUX 패턴의 4가지 요소를 적어주세요.

3. FLUX 패턴의 단점을 적어주세요.

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

1. A: MVC / B: 양방향 데이터 바인딩으로 프로젝트 규모가 커질수록 데이터 흐름을 추적하기 어렵다.

2. 
- action: 액션과 액션에 포함시킬 데이터를 말한다. 액션 타입과 데이터를 정의해 디스패처로 보낸다.
- dispatcher: 액션을 스토어에 보낸다. 콜백 함수 형태다. **애플리케이션 내에서 단 하나만 존재**해야 하며, 중앙 집중식으로 액션을 관리한다.
- store: 실제 값과 상태를 변경할 수 있는 메서드를 가지고 있다.
- view: 컴포넌트에 해당하는 부분으로, 스토어의 데이터를 화면에 렌더링하거나 액션을 호출해 상태를 업데이트한다.

3. 사용자의 입력에 따라 데이터를 갱신하고 화면을 어떻게 업데이트해야 할지도 코드로 작성해야 하므로 코드 양이 많아지고 개발자도 번거롭다.

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by khj0426** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
MVC패턴에서 애플리케이션이 커질 때 양방향의 model-view관계가 얽혀 상태를 추적하기 힘든 문제
action.dispatch,store,view
flux 패턴에서 하나의 상태를 만들고 관리하기 까지 많은 코드의 양이 들어간다.

</div>
</details>
