### ISSUE TITLE
[5장][효중] 리액트와 상태 관리 라이브러리

### ISSUE THREAD

**Issue by khj0426** [prgrms-web-devcourse/FEDC4-Modern-React-Study#54]
### 퀴즈

- FLUX패턴에 대해 설명해주세요

- useState와 useReducer를 이용한 상태 관리는 한계점이 존재하는데 어떤 것일까요?

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
정답 설명
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. FLUX 패턴은 action, dispatcher, store, view로 구성된 아키텍처로, 단방향 데이터 바인딩 형태를 띄고 있어 데이터 흐름을 추적하기 쉽다는 장점이 있다.

2. 컴포넌트 내부에서만 범위가 동작하기 때문에 지역 범위라고 볼 수 있다. 따라서 여러 컴포넌트에서 공유하려면 props을 통해 전달해야 하는 번거로움이 있다.

</div>
</details>
