### ISSUE TITLE
[10장][효리] 리액트 17과 18의 변경 사항 살펴보기

### ISSUE THREAD

**Issue by hyoribogo** [prgrms-web-devcourse/FEDC4-Modern-React-Study#57]
### 퀴즈

다음 코드의 console 출력 결과를 순서대로 작성하세요. (개발 환경에서의 strict mode를 배제하고 생각합니다.)

```tsx
import { useEffect, useRef } from 'react'

function Event() {
  const ref = useRef<HTMLDivElement>(null)
  useEffect(() => {
    if (!ref.current) return

    ref.current.addEventListener('click', () => console.log('부모 요소 클릭됨')) // 이벤트 추가

    return () => {
      if (!ref.current) return

      ref.current.removeEventListener('click', () => {}) // 이벤트 제거
    }
  }, [])

  return (
    <div
      className="parents bg-black w-24 h-24 relative mt-5 ml-5"
      ref={ref}>
      <div
        className="middle w-full h-full"
        onClick={() => {
          console.log('중간 요소 클릭됨')
        }}>
        <div
          onClick={(e) => {
            console.log('자식 요소 클릭됨')
            e.stopPropagation()
          }}
          className="children w-full h-full"></div>
      </div>
    </div>
  )
}

export default Event
```

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

## 정답

<img src='https://github.com/prgrms-web-devcourse/FEDC4-Modern-React-Study/assets/97094709/ceacc745-630b-4dab-a400-52f850957265' width='300' />

부모 요소 클릭됨
자식 요소 클릭됨

## 풀이

자식-부모가 아닌 부모-자식 순서로 역전된 이유는 이벤트 위임 때문입니다. react는 이벤트 위임을 사용해 root(혹은 document)에 등록하는데, 부모요소는 react가 관리하지 않으므로 그냥 단순히 요소에 등록되어있습니다. 따라서 이벤트 순서상 부모 요소->root 요소 이므로 부모요소가 먼저 출력되는것입니다.

stopPropagation 함수가 중간 요소를 막고, 부모 요소를 막지 못하는 이유는 각각 상이합니다. 먼저 부모 요소를 막지 못하는 것은 위와 유사하게 root 요소가 되어야만 stopPropagation 함수가 동작하기 때문입니다. 다음으로 중간 요소가 막히는 이유는 stopPropagation 함수는 래핑된 이벤트 객체의 함수이므로 내부적으로 react는 해당 함수의 실행 여부를 바탕으로 react가 관리하는 요소들의 버블링 여부를 결정해주기 때문입니다.

https://velog.io/@dujk68/react-%EC%97%90%EC%84%9C-%EC%9D%B4%EB%B2%A4%ED%8A%B8%EB%A5%BC-%EC%B2%98%EB%A6%AC%ED%95%98%EB%8A%94-%EB%B0%A9%EC%8B%9D#%EA%B3%A0%EB%AF%BC%ED%95%B4%EB%B3%B4%EA%B8%B0

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by khj0426** [comment]
부모요소 클릭됨
중간요소 클릭됨
자식요소 클릭됨
