### ISSUE TITLE
[11장][주하] Next.js 13과 리액트 18 (2)

### ISSUE THREAD

**Issue by hayamaster** [prgrms-web-devcourse/FEDC4-Modern-React-Study#68]
### 퀴즈

다음에 해당하는 내용을 답하세요.

<br/>

- 자바스크립트와 타입스크립트의 번들러
- 웹팩보다 700배, Vite보다 10배 빠르며, Rust로 작성되었다.
- vercel에서 제공하는 도구로 웹팩의 후계자를 자처한다.

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
터보 팩
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
터보팩
</div>
</details>

**Comment by khj0426** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
SWC
</div>
</details>
