### ISSUE TITLE
[11장][효리] Next.js 13과 리액트 18 (2)

### ISSUE THREAD

**Issue by hyoribogo** [prgrms-web-devcourse/FEDC4-Modern-React-Study#70]
### 퀴즈

서버 액션의 장점과 단점을 아는대로 작성해주세요.

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

## 장점
- Form 제출: 로그인, 회원가입과 같은 form의 로직을 Server Action 안에서 처리 가능
- 데이터 동기화: 외부 API로부터 데이터를 가져오거나 데이터베이스를 조회하는 코드를 Server Action에 배치
- 파일/이미지 업로드: 사용자의 업로드를 다루는 일을 서버 측에서 안전하게 할 수 있음

## 단점
- 복잡성 증가: 서버 측 코드를 추가해야 하기 때문에 개발 및 유지 관리가 더 복잡해질 수 있음
- 서버 부하 증가: 서버 측에서 많은 작업을 수행하기 때문에 서버 부하가 증가
- 디버깅 어려움: 클라이언트 측 코드보다 디버깅이 더 어려울 수 있음

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by khj0426** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
서버 액션은 서버 액션 시 실행하는 함수가 서버에서 빌드 되어 클라이언트 번들에 포함되지 않아 번들 크기에 이점이 있습니다.
클라이언트에서 바로 DB를 접근하는 것과 같은 작업을 할 수 있어 편리합니다
</div>
</details>

**Comment by hayamaster** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
장점
- 보안 강화
- 서버 통신 속도 개선

<br/>
<br/>
단점
- 서버 부하 증가
- 유지보수의 복잡성
</div>
</details>
