### ISSUE TITLE
[12장][효리] 모든 웹 개발자가 관심을 가져야 할 핵심 웹 지표

### ISSUE THREAD

**Issue by hyoribogo** [prgrms-web-devcourse/FEDC4-Modern-React-Study#75]
### 퀴즈

O,X 퀴즈입니다. 답과 그 이유를 적어주세요.

1. 이미지를 lazy 로딩하는 방식은 LCP 지표 점수에 도움이 된다.
2. 뷰포트에 보이는 메인 이미지를 Cloudicary 같은 이미지 최적화 서비스를 사용해 압축해 렌더링 하는 방식은 LCP 지표 점수에 도움이 된다.

### 답

<details>
<summary>정답</summary>
<div markdown="1">    

1. X, LCP의 이미지는 중요하지 않은 리소스로 분류하면 안된다. **그저 로딩 속도만 늦출 뿐** 지표 점수에는 도움이 되지 않는다.
2. X. 완전히 새로운 출처의 경우 **네트워크 커넥션부터 다시 수행**해야 하기 때문에 다른 출처에서 정제한 이미지를 가져오는 것은 최적화에 별로 좋은 영향을 미치지 않는다.

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by hayamaster** [comment]
1. X. 그저 로딩 속도만 늦출 뿐 지표 점수에는 도움이 되지 않는다.
2. X. 이미 연결이 맺어진 현재 출처와는 다르게, 완전히 새로운 출처의 경우에는 네트워크 커넥션부터 다시 수행해야한다.

**Comment by khj0426** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1 : X lazy loading을 하는 것은 LCP요소에 도움이 되지 않는다.
2 : X 외부 이미지의 경우(호스트가 다른 경우) 네트워크 커넥션부터 맺어야 하기 떄문에 도움이 되지 않는다 ( 같은 호스트는 도움 O)
</div>
</details>
