### ISSUE TITLE
[14장][주하] 웹사이트 보안을 위한 리액트와 웹페이지 보안 이슈

### ISSUE THREAD

**Issue by hayamaster** [prgrms-web-devcourse/FEDC4-Modern-React-Study#77]
### 퀴즈

리액트에서 XSS 문제를 피하는 방법에 관한 O/X 문제입니다.
답이 X인 문제는 옳은 답으로 고쳐주세요.

1. 제 3자가 삽입할 수 있는 HTML을 안전한 HTML 코드로 치환함으로 XSS를 예방하는 것을 sanitize 또는 escape라고 한다.
2. senitize는 차단할 태그와 목록을 일일히 나열해야하므로 보다 안전하다.
3. senitize에서 치환과정은 클라이언트에서 수행하는 것이 좋다.
4. 리액트에서는 JSX를 사용해 데이터를 렌더링할 때, 별도의 이스케이프 처리를 하지 않아도 기본적으로 XSS 보호를 받는다.

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
1. O
<br/>
2. X. senitize는 허용할 태그와 목록을 일일히 나열해야하므로 보다 안전하다.
<br/>
3. X. senitize에서 치환과정은 서버에서 수행하는 것이 좋다.
<br/>
4. O
</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1. O
2. O
3. X 서버
4. O 근데 댄저러슬리어쩌구는 안댐~

</div>
</details>

**Comment by khj0426** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1 O 
2 O
3 X _> 서버에서 작업을 수행하는 것이 좋다. curl로 직접적으로 요청을 날릴 수 있으니깐.?
4 O
</div>
</details>
