### ISSUE TITLE
[14장][효중] 웹사이트 보안을 위한 리액트와 웹페이지 보안 이슈

### ISSUE THREAD

**Issue by khj0426** [prgrms-web-devcourse/FEDC4-Modern-React-Study#80]
### 퀴즈

아래의 URL들 중에서 
https://www.example.com 
과same-site로 간주되는 URL은 무엇일까요?

1번 : [https://www.example.com:443/search?query=frontend](https://www.example.com/search?query=frontend)
2번 : [http://www.example.com:80/search?query=backend](http://www.example.com/search?query=backend)
3번 : [https://blog.example.com:443/search?query=AI](https://blog.example.com/search?query=AI)
4번 : https://www.example.com:80/search?query=AI

### 답

<details>
<summary>정답</summary>
<div markdown="1">    
동일 출처는 scheme, hostname, port가 모두 일치해야 합니다.
2번은 scheme가 다릅니다(HTTP), 3번은 hostname이 다르고 4번은 port가 다릅니다.

</div>
</details>

### 댓글 작성법

(다음과 같이 답을 작성해 댓글로 달아주세요)
&lt;details&gt;
&lt;summary&gt;정답&lt;/summary&gt;
&lt;div markdown="1"&gt;    
정답 설명
&lt;/div&gt;
&lt;/details&gt;

**Comment by hayamaster** [comment]
<details>
<summary>정답</summary>
<div markdown="1">
1번!
</div>
</details>

**Comment by hyoribogo** [comment]
<details>
<summary>정답</summary>
<div markdown="1">

1

</div>
</details>
